services:
  gateway:
    build: .
    command: uvicorn src.services.gateway.main:app --host 0.0.0.0 --port ${GATEWAY_PORT}
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    environment:
      - GATEWAY_URL=http://gateway:${GATEWAY_PORT}
      - SERVICE_REGISTRY={"science_qbank":[],"general_qbank":[],"generator":[]}
    networks:
      - qgen_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${GATEWAY_PORT}/health" ]
      interval: 5s
      timeout: 5s
      retries: 5

  qbank:
    build: .
    command: uvicorn src.services.qbank.main:app --host 0.0.0.0 --port ${QBANK_PORT}
    ports:
      - "${QBANK_PORT}:${QBANK_PORT}"
    environment:
      - SERVICE_NAME=general_qbank
      - SERVICE_PORT=${QBANK_PORT}
      - SERVICE_HOST=qbank
      - GATEWAY_URL=http://gateway:${GATEWAY_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - PRIMARY_GENERATOR=${PRIMARY_GENERATOR}
      - FALLBACK_GENERATOR=${FALLBACK_GENERATOR}
    depends_on:
      gateway:
        condition: service_healthy
    networks:
      - qgen_network

  generator:
    build: .
    command: uvicorn src.services.generator.main:app --host 0.0.0.0 --port ${GENERATOR_PORT}
    ports:
      - "${GENERATOR_PORT}:${GENERATOR_PORT}"
    environment:
      - SERVICE_PORT=${GENERATOR_PORT}
      - SERVICE_HOST=generator
      - GATEWAY_URL=http://gateway:${GATEWAY_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - PRIMARY_GENERATOR=${PRIMARY_GENERATOR}
      - FALLBACK_GENERATOR=${FALLBACK_GENERATOR}
    depends_on:
      gateway:
        condition: service_healthy
    networks:
      - qgen_network

  auth:
    build: .
    command: uvicorn src.services.auth.main:app --host 0.0.0.0 --port ${AUTH_PORT}
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    environment:
      - SERVICE_PORT=${AUTH_PORT}
      - SERVICE_HOST=auth
      - GATEWAY_URL=http://gateway:${GATEWAY_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_SECRET_KEY=${AUTH_SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
    depends_on:
      gateway:
        condition: service_healthy
    networks:
      - qgen_network

networks:
  qgen_network:
    driver: bridge
